In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.layers import Dense,Flatten,Conv2D,MaxPooling2D,Dropout,BatchNormalization

In [3]:
data_train = pd.read_csv('/content/train.csv')

data_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [13]:
data_test = pd.read_csv("/content/test.csv")
data_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
data_train.replace(['female','male'],[0,1],inplace=True)

data_train.fillna(20,inplace=True)

In [14]:
data_test.replace(['female','male'],[0,1],inplace=True)

data_test.fillna(20,inplace=True)

In [5]:
data_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,20,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,20,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,20,S

In [16]:
data_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,20,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,20,S
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,20,Q
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,20,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,20,S

In [6]:
X_train = np.array(data_train[['Pclass','Sex','Age','SibSp','Fare']])
Y_train = np.array(data_train[['Survived']])

In [18]:
X_test = np.array(data_test[['Pclass','Sex','Age','SibSp','Fare']])

In [24]:
Y_test = pd.read_csv("/content/gender_submission.csv")
Y_test = Y_test[["Survived"]].to_numpy()

In [25]:

train_dataset = tf.data.Dataset.from_tensor_slices((X_train,Y_train)).batch(32).shuffle(1000)
test_dataset = tf.data.Dataset.from_tensor_slices((X_test,Y_test)).batch(32)

In [26]:
class MyModel(tf.keras.Model):
  def __init__(self):
    super().__init__()
    # self.conv1 = Conv2D(64,(2,2), activation="relu", padding="same")
    # self.conv2 = Conv2D(64, (4,4), activation="relu", padding="same")
    # self.conv3 = Conv2D(128, (2,2), activation="relu", padding="same")
    # self.conv4 = Conv2D(32, (3,3), activation="relu", padding="same")
    # self.b1 = BatchNormalization()
    # self.b2 = BatchNormalization()
    # self.b3 = BatchNormalization()
    # self.b4 = BatchNormalization()
    # self.m = MaxPooling2D(3,3)
    # self.dropout1 = Dropout(0.3)
    # self.dropout2 = Dropout(0.5)
    # self.dropout3 = Dropout(0.4)
    self.dense1 = Dense(5, activation='sigmoid')
    self.dense2 = Dense(18, activation='relu')
    self.dense3 = Dense(10, activation='softmax')
    self.dense4 = Dense(2, activation='softmax')
    #self.dense2 = Dense(10, activation='softmax')
    #self.f = Flatten()
  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    x = self.dense3(x)
    x = self.dense4(x)
    return x

model = MyModel()

In [36]:
# Main loss function
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)


# Metrics
train_loss = tf.keras.metrics.Mean()
test_loss = tf.keras.metrics.Mean()

train_acc = tf.keras.metrics.SparseCategoricalAccuracy()
test_acc = tf.keras.metrics.SparseCategoricalAccuracy()

In [37]:

@tf.function
def train(sample_data , label):
    with tf.GradientTape() as tape :
      prediction = model(sample_data)
      loss = loss_function(label , prediction)
    gradients = tape.gradient(loss , model.trainable_variables)
    optimizer.apply_gradients(grads_and_vars= zip(gradients , model.trainable_variables))

    train_loss(loss)
    train_acc(label , prediction)

In [38]:
@tf.function
def test(sample_data , label):
  prediction = model(sample_data)
  loss = loss_function(y_true=label , y_pred=prediction)
  test_loss(loss )
  test_acc(label , prediction)

In [40]:
epochs = 100
for epoch in range(epochs):
  train_loss.reset_states()
  train_acc.reset_states()
  test_loss.reset_states()
  test_acc.reset_states()

  #train
  for data , label in train_dataset :
    train(data , label)

  # test
  for data , label in test_dataset :
    test(data , label)

  print("epoch:" , epoch + 1  ,
        f"Train Loss: {train_loss.result()}" ,
        f"Train Acc: {train_acc.result()}" ,
        f"Test Loss: {test_loss.result()}" ,
        f"Test Acc: {test_acc.result()}"
        )

epoch: 1 Train Loss: 0.3957178592681885 Train Acc: 0.8271604776382446 Test Loss: 0.29011598229408264 Test Acc: 0.9043062329292297
epoch: 2 Train Loss: 0.39304134249687195 Train Acc: 0.8316498398780823 Test Loss: 0.32484379410743713 Test Acc: 0.8875598311424255
epoch: 3 Train Loss: 0.3921055197715759 Train Acc: 0.8249158263206482 Test Loss: 0.26781052350997925 Test Acc: 0.9138755798339844
epoch: 4 Train Loss: 0.3946414887905121 Train Acc: 0.8249158263206482 Test Loss: 0.3359014093875885 Test Acc: 0.8827751278877258
epoch: 5 Train Loss: 0.38886022567749023 Train Acc: 0.8282828330993652 Test Loss: 0.3332648277282715 Test Acc: 0.8851674795150757
epoch: 6 Train Loss: 0.3967267870903015 Train Acc: 0.8215488195419312 Test Loss: 0.3088187277317047 Test Acc: 0.8851674795150757
epoch: 7 Train Loss: 0.39307063817977905 Train Acc: 0.8305274844169617 Test Loss: 0.2865385115146637 Test Acc: 0.9473684430122375
epoch: 8 Train Loss: 0.40264126658439636 Train Acc: 0.8215488195419312 Test Loss: 0.29184970259666443 Test Acc: 0.940191388130188
epoch: 9 Train Loss: 0.4099765717983246 Train Acc: 0.8271604776382446 Test Loss: 0.40571117401123047 Test Acc: 0.8157894611358643
epoch: 10 Train Loss: 0.41190338134765625 Train Acc: 0.8125701546669006 Test Loss: 0.2660983204841614 Test Acc: 0.9521530866622925
epoch: 11 Train Loss: 0.3965250849723816 Train Acc: 0.8249158263206482 Test Loss: 0.2918550670146942 Test Acc: 0.8971291780471802
epoch: 12 Train Loss: 0.39332327246665955 Train Acc: 0.8215488195419312 Test Loss: 0.30323171615600586 Test Acc: 0.9019138813018799
epoch: 13 Train Loss: 0.39088302850723267 Train Acc: 0.8282828330993652 Test Loss: 0.306367963552475 Test Acc: 0.9497607946395874
epoch: 14 Train Loss: 0.3863060772418976 Train Acc: 0.8338944911956787 Test Loss: 0.3194289207458496 Test Acc: 0.9019138813018799
epoch: 15 Train Loss: 0.3909720778465271 Train Acc: 0.8282828330993652 Test Loss: 0.33219972252845764 Test Acc: 0.880382776260376
epoch: 16 Train Loss: 0.391155481338501 Train Acc: 0.8338944911956787 Test Loss: 0.3104279339313507 Test Acc: 0.9066985845565796
epoch: 17 Train Loss: 0.3869188725948334 Train Acc: 0.8327721953392029 Test Loss: 0.3063306212425232 Test Acc: 0.9066985845565796
epoch: 18 Train Loss: 0.3891308903694153 Train Acc: 0.8260381817817688 Test Loss: 0.3308480381965637 Test Acc: 0.8899521827697754
epoch: 19 Train Loss: 0.3917383551597595 Train Acc: 0.8294051885604858 Test Loss: 0.31925728917121887 Test Acc: 0.940191388130188
epoch: 20 Train Loss: 0.4064086973667145 Train Acc: 0.8193041682243347 Test Loss: 0.28967148065567017 Test Acc: 0.9425837397575378
epoch: 21 Train Loss: 0.4036118984222412 Train Acc: 0.8237934708595276 Test Loss: 0.38684484362602234 Test Acc: 0.8373205661773682
epoch: 22 Train Loss: 0.4076717495918274 Train Acc: 0.8193041682243347 Test Loss: 0.3042244017124176 Test Acc: 0.9114832282066345
epoch: 23 Train Loss: 0.38900962471961975 Train Acc: 0.8305274844169617 Test Loss: 0.28226467967033386 Test Acc: 0.9497607946395874
epoch: 24 Train Loss: 0.38624897599220276 Train Acc: 0.8305274844169617 Test Loss: 0.3167521357536316 Test Acc: 0.9234449863433838
epoch: 25 Train Loss: 0.3879248797893524 Train Acc: 0.8260381817817688 Test Loss: 0.31156060099601746 Test Acc: 0.8923444747924805
epoch: 26 Train Loss: 0.38837677240371704 Train Acc: 0.8350168466567993 Test Loss: 0.2963358759880066 Test Acc: 0.9090909361839294
epoch: 27 Train Loss: 0.4123920798301697 Train Acc: 0.8058361411094666 Test Loss: 0.2574825882911682 Test Acc: 0.9760765433311462
epoch: 28 Train Loss: 0.39765289425849915 Train Acc: 0.8237934708595276 Test Loss: 0.2984957993030548 Test Acc: 0.9545454382896423
epoch: 29 Train Loss: 0.4036443531513214 Train Acc: 0.8294051885604858 Test Loss: 0.3261865973472595 Test Acc: 0.8899521827697754
epoch: 30 Train Loss: 0.3909173905849457 Train Acc: 0.8260381817817688 Test Loss: 0.32439807057380676 Test Acc: 0.89952152967453
epoch: 31 Train Loss: 0.3910042643547058 Train Acc: 0.8260381817817688 Test Loss: 0.2876691222190857 Test Acc: 0.9258373379707336
epoch: 32 Train Loss: 0.38907650113105774 Train Acc: 0.8282828330993652 Test Loss: 0.297797828912735 Test Acc: 0.9066985845565796
epoch: 33 Train Loss: 0.3859332203865051 Train Acc: 0.8350168466567993 Test Loss: 0.31874099373817444 Test Acc: 0.9330143332481384
epoch: 34 Train Loss: 0.3861922323703766 Train Acc: 0.8305274844169617 Test Loss: 0.3016822636127472 Test Acc: 0.9066985845565796
epoch: 35 Train Loss: 0.39086490869522095 Train Acc: 0.8294051885604858 Test Loss: 0.3117563724517822 Test Acc: 0.89952152967453
epoch: 36 Train Loss: 0.39000654220581055 Train Acc: 0.8316498398780823 Test Loss: 0.31258314847946167 Test Acc: 0.8971291780471802
epoch: 37 Train Loss: 0.39543887972831726 Train Acc: 0.8204264640808105 Test Loss: 0.3115505576133728 Test Acc: 0.8947368264198303
epoch: 38 Train Loss: 0.3893119692802429 Train Acc: 0.8305274844169617 Test Loss: 0.31883522868156433 Test Acc: 0.8851674795150757
epoch: 39 Train Loss: 0.39443036913871765 Train Acc: 0.8305274844169617 Test Loss: 0.3079254627227783 Test Acc: 0.9162679314613342
epoch: 40 Train Loss: 0.39129209518432617 Train Acc: 0.8294051885604858 Test Loss: 0.32552000880241394 Test Acc: 0.9282296895980835
epoch: 41 Train Loss: 0.3910672068595886 Train Acc: 0.8327721953392029 Test Loss: 0.3007761538028717 Test Acc: 0.9330143332481384
epoch: 42 Train Loss: 0.4043963849544525 Train Acc: 0.8215488195419312 Test Loss: 0.26923826336860657 Test Acc: 0.9688995480537415
epoch: 43 Train Loss: 0.39802858233451843 Train Acc: 0.8282828330993652 Test Loss: 0.3115222454071045 Test Acc: 0.9019138813018799
epoch: 44 Train Loss: 0.3980993330478668 Train Acc: 0.8350168466567993 Test Loss: 0.2709994912147522 Test Acc: 0.9282296895980835
epoch: 45 Train Loss: 0.3867311179637909 Train Acc: 0.8294051885604858 Test Loss: 0.30532902479171753 Test Acc: 0.9138755798339844
epoch: 46 Train Loss: 0.38882189989089966 Train Acc: 0.8305274844169617 Test Loss: 0.30960777401924133 Test Acc: 0.9497607946395874
epoch: 47 Train Loss: 0.3826406002044678 Train Acc: 0.8361391425132751 Test Loss: 0.3186226785182953 Test Acc: 0.8923444747924805
epoch: 48 Train Loss: 0.38335373997688293 Train Acc: 0.8361391425132751 Test Loss: 0.33996301889419556 Test Acc: 0.8851674795150757
epoch: 49 Train Loss: 0.3890739977359772 Train Acc: 0.8282828330993652 Test Loss: 0.30709201097488403 Test Acc: 0.8971291780471802
epoch: 50 Train Loss: 0.38753804564476013 Train Acc: 0.8316498398780823 Test Loss: 0.3271729648113251 Test Acc: 0.8827751278877258
epoch: 51 Train Loss: 0.3961230218410492 Train Acc: 0.8215488195419312 Test Loss: 0.3299556374549866 Test Acc: 0.8827751278877258
epoch: 52 Train Loss: 0.3955235481262207 Train Acc: 0.8294051885604858 Test Loss: 0.31264427304267883 Test Acc: 0.9043062329292297
epoch: 53 Train Loss: 0.40580564737319946 Train Acc: 0.8215488195419312 Test Loss: 0.27287986874580383 Test Acc: 0.9449760913848877
epoch: 54 Train Loss: 0.38540101051330566 Train Acc: 0.8350168466567993 Test Loss: 0.2893960475921631 Test Acc: 0.9497607946395874
epoch: 55 Train Loss: 0.39463749527931213 Train Acc: 0.8249158263206482 Test Loss: 0.3270699083805084 Test Acc: 0.880382776260376
epoch: 56 Train Loss: 0.39738693833351135 Train Acc: 0.8305274844169617 Test Loss: 0.2867063581943512 Test Acc: 0.9019138813018799
epoch: 57 Train Loss: 0.3981468677520752 Train Acc: 0.8226711750030518 Test Loss: 0.25956031680107117 Test Acc: 0.980861246585846
epoch: 58 Train Loss: 0.4021185338497162 Train Acc: 0.8226711750030518 Test Loss: 0.2878809869289398 Test Acc: 0.9688995480537415
epoch: 59 Train Loss: 0.39586034417152405 Train Acc: 0.8249158263206482 Test Loss: 0.25490158796310425 Test Acc: 0.9545454382896423
epoch: 60 Train Loss: 0.4027476906776428 Train Acc: 0.8181818127632141 Test Loss: 0.28400588035583496 Test Acc: 0.9665071964263916
epoch: 61 Train Loss: 0.39339679479599 Train Acc: 0.8237934708595276 Test Loss: 0.31217461824417114 Test Acc: 0.9354066848754883
epoch: 62 Train Loss: 0.38308995962142944 Train Acc: 0.8294051885604858 Test Loss: 0.29030483961105347 Test Acc: 0.9210526347160339
epoch: 63 Train Loss: 0.39495471119880676 Train Acc: 0.8327721953392029 Test Loss: 0.3591316342353821 Test Acc: 0.89952152967453
epoch: 64 Train Loss: 0.40536004304885864 Train Acc: 0.8316498398780823 Test Loss: 0.30099645256996155 Test Acc: 0.9138755798339844
epoch: 65 Train Loss: 0.3971106708049774 Train Acc: 0.8249158263206482 Test Loss: 0.2709287106990814 Test Acc: 0.9114832282066345
epoch: 66 Train Loss: 0.4025166928768158 Train Acc: 0.8181818127632141 Test Loss: 0.2700559198856354 Test Acc: 0.9569377899169922
epoch: 67 Train Loss: 0.38931354880332947 Train Acc: 0.8305274844169617 Test Loss: 0.30019479990005493 Test Acc: 0.9066985845565796
epoch: 68 Train Loss: 0.39332571625709534 Train Acc: 0.8226711750030518 Test Loss: 0.31662359833717346 Test Acc: 0.9306219816207886
epoch: 69 Train Loss: 0.3962392807006836 Train Acc: 0.8193041682243347 Test Loss: 0.29650744795799255 Test Acc: 0.9162679314613342
epoch: 70 Train Loss: 0.3919060528278351 Train Acc: 0.8237934708595276 Test Loss: 0.31107956171035767 Test Acc: 0.8899521827697754
epoch: 71 Train Loss: 0.38743355870246887 Train Acc: 0.8350168466567993 Test Loss: 0.2975400388240814 Test Acc: 0.9473684430122375
epoch: 72 Train Loss: 0.38776832818984985 Train Acc: 0.8282828330993652 Test Loss: 0.29218149185180664 Test Acc: 0.9043062329292297
epoch: 73 Train Loss: 0.38724178075790405 Train Acc: 0.8338944911956787 Test Loss: 0.29624396562576294 Test Acc: 0.9162679314613342
epoch: 74 Train Loss: 0.3882932662963867 Train Acc: 0.8305274844169617 Test Loss: 0.30467358231544495 Test Acc: 0.9282296895980835
epoch: 75 Train Loss: 0.3916783034801483 Train Acc: 0.8294051885604858 Test Loss: 0.2947531044483185 Test Acc: 0.9449760913848877
epoch: 76 Train Loss: 0.38423630595207214 Train Acc: 0.8271604776382446 Test Loss: 0.2740404009819031 Test Acc: 0.9066985845565796
epoch: 77 Train Loss: 0.38570430874824524 Train Acc: 0.8327721953392029 Test Loss: 0.30019259452819824 Test Acc: 0.9425837397575378
epoch: 78 Train Loss: 0.38505059480667114 Train Acc: 0.8372614979743958 Test Loss: 0.29873546957969666 Test Acc: 0.9138755798339844
epoch: 79 Train Loss: 0.3827032446861267 Train Acc: 0.8361391425132751 Test Loss: 0.32454362511634827 Test Acc: 0.9019138813018799
epoch: 80 Train Loss: 0.396640807390213 Train Acc: 0.8271604776382446 Test Loss: 0.30582180619239807 Test Acc: 0.9114832282066345
epoch: 81 Train Loss: 0.3926198184490204 Train Acc: 0.8316498398780823 Test Loss: 0.28559643030166626 Test Acc: 0.9234449863433838
epoch: 82 Train Loss: 0.38835158944129944 Train Acc: 0.8338944911956787 Test Loss: 0.2777724862098694 Test Acc: 0.9641148447990417
epoch: 83 Train Loss: 0.40215858817100525 Train Acc: 0.8226711750030518 Test Loss: 0.3287111222743988 Test Acc: 0.8971291780471802
epoch: 84 Train Loss: 0.4006199538707733 Train Acc: 0.8237934708595276 Test Loss: 0.30201587080955505 Test Acc: 0.9019138813018799
epoch: 85 Train Loss: 0.39597442746162415 Train Acc: 0.8282828330993652 Test Loss: 0.3257668912410736 Test Acc: 0.8971291780471802
epoch: 86 Train Loss: 0.38915055990219116 Train Acc: 0.8338944911956787 Test Loss: 0.33532047271728516 Test Acc: 0.8899521827697754
epoch: 87 Train Loss: 0.38522329926490784 Train Acc: 0.8350168466567993 Test Loss: 0.29239335656166077 Test Acc: 0.8923444747924805
epoch: 88 Train Loss: 0.39111998677253723 Train Acc: 0.8271604776382446 Test Loss: 0.31330862641334534 Test Acc: 0.9497607946395874
epoch: 89 Train Loss: 0.39058130979537964 Train Acc: 0.8350168466567993 Test Loss: 0.3032059967517853 Test Acc: 0.9425837397575378
epoch: 90 Train Loss: 0.41310054063796997 Train Acc: 0.8249158263206482 Test Loss: 0.31588083505630493 Test Acc: 0.8971291780471802
epoch: 91 Train Loss: 0.38604140281677246 Train Acc: 0.8294051885604858 Test Loss: 0.30203738808631897 Test Acc: 0.9043062329292297
epoch: 92 Train Loss: 0.39464420080184937 Train Acc: 0.8204264640808105 Test Loss: 0.36723634600639343 Test Acc: 0.8588516712188721
epoch: 93 Train Loss: 0.42436572909355164 Train Acc: 0.8215488195419312 Test Loss: 0.2796652615070343 Test Acc: 0.9186602830886841
epoch: 94 Train Loss: 0.3895031809806824 Train Acc: 0.8338944911956787 Test Loss: 0.3225221633911133 Test Acc: 0.9186602830886841
epoch: 95 Train Loss: 0.3959921896457672 Train Acc: 0.8305274844169617 Test Loss: 0.3206797242164612 Test Acc: 0.9043062329292297
epoch: 96 Train Loss: 0.3835725784301758 Train Acc: 0.8361391425132751 Test Loss: 0.31305748224258423 Test Acc: 0.9019138813018799
epoch: 97 Train Loss: 0.3851640224456787 Train Acc: 0.8361391425132751 Test Loss: 0.30724722146987915 Test Acc: 0.9019138813018799
epoch: 98 Train Loss: 0.3971458077430725 Train Acc: 0.8271604776382446 Test Loss: 0.2889937460422516 Test Acc: 0.959330141544342
epoch: 99 Train Loss: 0.3883362412452698 Train Acc: 0.8282828330993652 Test Loss: 0.31865113973617554 Test Acc: 0.9162679314613342
epoch: 100 Train Loss: 0.3843575417995453 Train Acc: 0.8294051885604858 Test Loss: 0.32890206575393677 Test Acc: 0.8875598311424255